[?1049h[?1h=[1;57r[?12;25h[?12l[?25h[27m[m[H[2J[?25l[57;1H".git/COMMIT_EDITMSG" 87L, 3738C[2;1H[34m# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# Explicit paths specified without -i nor -o; assuming --only paths...
# On branch [m[35mmaster[m
[34m# [m[35mChanges to be committed:[m
[34m#   (use "git reset HEAD <file>..." to unstage)
#
#       [m[32mnew file[m[34m: [m[31m  root/firmware/dvb-fe-avl2108.fw[m
[34m#
# [m[35mChanged but not updated:[m
[34m#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       [m[32mmodified[m[34m: [m[31m  make/release.mk[m
[34m#       [m[32mmodified[m[34m: [m[31m  make/release_neutrino.mk[m
[34m#       [m[32mmodified[m[34m: [m[31m  root/release/rcS_atevio7500[m
[34m#       [m[32mmodified[m[34m: [m[31m  root/release/rcS_neutrino_octagon1008[m
[34m#       [m[32mmodified[m[34m: [m[31m  root/release/rcS_octagon1008[m
[34m#       [m[32mmodified[m[34m: [m[31m  root/release/rcS_stm23_atevio7500[m
[34m#       [m[32mmodified[m[34m: [m[31m  root/release/rcS_stm23_neutrino_atevio7500[m
[34m#       [m[32mmodified[m[34m: [m[31m  root/release/rcS_stm23_neutrino_octagon1008[m
[34m#       [m[32mmodified[m[34m: [m[31m  ../driver/Makefile[m
[34m#       [m[32mmodified[m[34m: [m[31m  ../driver/frontcontroller/nuvoton/nuvoton_asc.c[m
[34m#       [m[32mmodified[m[34m: [m[31m  ../driver/frontcontroller/nuvoton/nuvoton_asc.h[m
[34m#       [m[32mmodified[m[34m: [m[31m  ../driver/frontcontroller/nuvoton/nuvoton_file.c[m
[34m#       [m[32mmodified[m[34m: [m[31m  ../driver/frontcontroller/nuvoton/nuvoton_main.c[m
[34m#       [m[32mmodified[m[34m: [m[31m  ../driver/frontends/Makefile[m
[34m#
# [m[35mUntracked files:[m
[34m#   (use "git add <file>..." to include in what will be committed)
#
#       ../apps/enigma2-nightly.patched/
#       ../apps/misc/tools/libeplayer3/Makefile
#       ../apps/misc/tools/libeplayer3/eplayer3
#       ../apps/misc/tools/libeplayer3/meta
#       ../apps/misc/tools/libmme_host/Makefile
#       ../apps/misc/tools/libmmeimage/Makefile
#       ../apps/misc/tools/vfdctl/Makefile
#       ../apps/misc/tools/vfdctl/vfdctl
#       ffmpeg-0.6/
#       libass-0.9.11/
#       linux-sh4-2.6.32.16_stm24_0205/
#       root/firmware/dvb-fe-stv6306.fw
#       ttt
#       ../driver/avs/modules.order
#       ../driver/boxtype/modules.order
#       ../driver/bpamem/modules.order
#       ../driver/cic/modules.order
#       ../driver/compcache/modules.order
#       ../driver/e2_proc/modules.order
#       ../driver/frontcontroller/micom/modules.order
#       ../driver/frontcontroller/modules.order
#       ../driver/frontends/avl2108/
#       ../driver/frontends/modules.order
#       ../driver/include/player2[m[57;229H1,0-1      Anfang[1;1H[?12l[?25h[?25l[57;229H2,1  [2;1H[?12l[?25h[?25l[57;229H3[3;1H[?12l[?25h[?25l[57;229H4[4;1H[?12l[?25h[?25l[57;1HBitte  :quit<Enter>  eingeben um Vim zu verlassen[57;229H[K[57;229H4,1[8CAnfang[4;1H[?12l[?25h[?25l[57;229H5[5;1H[?12l[?25h[?25l[57;229H6[6;1H[?12l[?25h[?25l[57;229H7[7;1H[?12l[?25h[?25l[57;1H[K[57;1H:[?12l[?25hq[?25l[?12l[?25h[?25l[57;1H[K[57;1H[?1l>[?12l[?25h[?1049l