/************************************************************************
COPYRIGHT (C) STMicroelectronics 2008

Source file name : monitor_types.h - external interface definitions
Author :           Julian

Date        Modification                                    Name
----        ------------                                    --------
24-Jul-08   Created                                         Julian

************************************************************************/

#ifndef H_MONITOR_TYPES
#define H_MONITOR_TYPES

#define MONITOR_PARAMETER_COUNT                 4
#define MONITOR_EVENT_REPORT_ON_REQUEST         0x00000100

typedef enum monitor_subsystem_e
{
    MONITOR_DISABLE_ALL                         = 0x00000000,
    MONITOR_ENABLE_ALL                          = 0x000f0000,
    MONITOR_AUDIO_FORMAT_MONITORING             = 0x00010000,
    MONITOR_AUDIO_DECODER_PERFORMANCE           = 0x00020000,
    MONITOR_VIDEO_SIGNAL_ACQUISITION            = 0x00040000,
    MONITOR_VIDEO_PROCESSING                    = 0x00080000,
    MONITOR_SYSTEM_GENERIC                      = 0x00100000
} monitor_subsystem_t;

typedef enum monitor_event_code_e
{
    MONITOR_EVENT_AUDIO_SIGNAL_ACQUIRED         = MONITOR_AUDIO_FORMAT_MONITORING       | 0x00000000,
    MONITOR_EVENT_AUDIO_SIGNAL_LOST             = MONITOR_AUDIO_FORMAT_MONITORING       | 0x00000001,
    MONITOR_EVENT_AUDIO_FORMAT_DETECTED         = MONITOR_AUDIO_FORMAT_MONITORING       | 0x00000002,
    MONITOR_EVENT_AUDIO_FORMAT_UNKNOWN          = MONITOR_AUDIO_FORMAT_MONITORING       | 0x00000003,

    MONITOR_EVENT_AUDIO_INITIALIZATION_START    = MONITOR_AUDIO_DECODER_PERFORMANCE     | 0x00000004,
    MONITOR_EVENT_AUDIO_SHUTDOWN_COMPLETE       = MONITOR_AUDIO_DECODER_PERFORMANCE     | 0x00000005,
    MONITOR_EVENT_AUDIO_SAMPLING_RATE_CHANGE    = MONITOR_AUDIO_DECODER_PERFORMANCE     | 0x00000006,
    MONITOR_EVENT_AUDIO_SAMPLES_PROCESSED       = MONITOR_AUDIO_DECODER_PERFORMANCE     | MONITOR_EVENT_REPORT_ON_REQUEST   | 0x00000007,
    MONITOR_EVENT_AUDIO_POTENTIAL_ARTIFACT      = MONITOR_AUDIO_DECODER_PERFORMANCE     | 0x00000008,

    MONITOR_EVENT_VIDEO_FIRST_FIELD_ACQUIRED    = MONITOR_VIDEO_SIGNAL_ACQUISITION      | 0x00000009,
    MONITOR_EVENT_VIDEO_ACQUISITION_STOPPED     = MONITOR_VIDEO_SIGNAL_ACQUISITION      | 0x0000000a,
    MONITOR_EVENT_VIDEO_SIGNAL_ACQUIRED         = MONITOR_VIDEO_SIGNAL_ACQUISITION      | 0x0000000b,
    MONITOR_EVENT_VIDEO_SIGNAL_LOST             = MONITOR_VIDEO_SIGNAL_ACQUISITION      | 0x0000000c,
    MONITOR_EVENT_VIDEO_FIELDS_EXPECTED         = MONITOR_VIDEO_SIGNAL_ACQUISITION      | MONITOR_EVENT_REPORT_ON_REQUEST   | 0x0000000d,
    MONITOR_EVENT_VIDEO_FIELDS_DROPPED          = MONITOR_VIDEO_SIGNAL_ACQUISITION      | MONITOR_EVENT_REPORT_ON_REQUEST   | 0x0000000e,
    MONITOR_EVENT_VIDEO_TNR_SETTING             = MONITOR_VIDEO_SIGNAL_ACQUISITION      | MONITOR_EVENT_REPORT_ON_REQUEST   | 0x0000000f,
    MONITOR_EVENT_VIDEO_DEINTERLACER_SETTING    = MONITOR_VIDEO_SIGNAL_ACQUISITION      | MONITOR_EVENT_REPORT_ON_REQUEST   | 0x00000010,

    MONITOR_EVENT_INFORMATION                   = MONITOR_SYSTEM_GENERIC                | 0x00000011
} monitor_event_code_t;

#endif
